CREATE DATABASE IF NOT EXISTS usinagem CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE usinagem;


-- Users
CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
cpf VARCHAR(14) NOT NULL UNIQUE, -- formatted as 000.000.000-00 or plain digits
password_hash VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;


-- Production Records
CREATE TABLE IF NOT EXISTS records (
id INT AUTO_INCREMENT PRIMARY KEY,
tool VARCHAR(100) NOT NULL,
machine VARCHAR(100) NOT NULL,
parts_produced INT NOT NULL,
entry_date DATE NOT NULL,
exit_date DATE NOT NULL,
entry_time TIME NOT NULL,
exit_time TIME NOT NULL,
user_id INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_records_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;